from .base import Manager

from ..models import autogenerated as model


class TaskManager(Manager):
    model = model.Task

class TaskPropertiesManager(Manager):
    model = model.TaskProperties

class SetManager(Manager):
    model = model.SetI
