from .base import Manager

from ..models import autogenerated as model


class UserManager(Manager):
    model = model.User
    
class MasterManager(Manager):
    model = model.Master
    
class GymerManager(Manager):
    model = model.Gymer
    
class MasterGymManager(Manager):
    model = model.MasterGym
    
