from .base import Manager

from ..models import autogenerated as model


class ExerciseManager(Manager):
    model = model.Exercise

class LinkExerciseManager(Manager):
    model = model.LinkExercise

class LinkManager(Manager):
    model = model.Link
