from .base import Manager

from ..models import autogenerated as model


class ExerciseManager(Manager):
    model = model.Exercise

class ExerciseDescManager(Manager):
    model = model.ExerciseDesc

class LinkCardManager(Manager):
    model = model.LinkCard

class LinkManager(Manager):
    model = model.LinkCard
