from .base import Manager

from ..models import autogenerated as model


class TaskManager(Manager):
    model = model.Task

class TaskProperties(Manager):
    model = model.TaskProperties

class SetManager(Manager):
    model = model.Set
